DROP TABLE IF EXISTS `user`;

CREATE TABLE `user`
(
    id BIGINT NOT NULL COMMENT '主键ID',
    username VARCHAR(256) NULL DEFAULT NULL COMMENT '昵称',
    userAccount VARCHAR(256) NULL DEFAULT NULL COMMENT '账号',
    avatarUrl VARCHAR(256) NULL DEFAULT NULL COMMENT '头像',
    gender tinyint  COMMENT '性别',
    userPassword VARCHAR(256) NULL DEFAULT NULL COMMENT '密码',
    phone VARCHAR(256) NULL DEFAULT NULL COMMENT '电话',
    email VARCHAR(256) NULL DEFAULT NULL COMMENT '邮箱',
    userStatus int  DEFAULT 0 COMMENT '是否有效（比如被封号之类）',
    createTime DATETIME DEFAULT CURRENT_TIMESTAMP NULL COMMENT '创建时间',
    updateTime DATETIME DEFAULT CURRENT_TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    isDelete tinyint NULL DEFAULT 0 COMMENT '是否删除',
    userRole tinyint NULL DEFAULT 0 COMMENT '角色',
    PRIMARY KEY (id)
);

